char_list = ["ohm", "ohmf", "ohmm"]

[ohm]
name = "歐姆巴"
color = "#F5D80A"
directory = "ohm"

sprites_list = ["Normal", "happy", "sad"]
sprites_png_list = ["ohm_Normal.png", "ohm_happy.png", "ohm_sad.png"]
sprites_png = ["ohm_Normal.png", "ohm_happy.png", "ohm_sad.png"]
[ohmf]
name = "歐姆爸"
color = "#F5D80A"
directory = "ohmf"

sprites_list = ["Normal", "happy", "sad"]
sprites_png_list = ["ohmf_Normal.png", "ohmf_happy.png", "ohmf_sad.png"]
sprites_png = ["ohmf_Normal.png", "ohmf_happy.png", "ohmf_sad.png"]
[ohmm]
name = "歐姆媽"
color = "#F5D80A"
directory = "ohmm"

sprites_list = ["Normal", "happy", "sad"]
sprites_png_list = ["ohmm_Normal.png", "ohmm_happy.png", "ohmm_sad.png"]
sprites_png = ["ohmm_Normal.png", "ohmm_happy.png", "ohmm_sad.png"]
