[Start]
script = [
    { action = "Music", music_id = "BGM_1"},
    { action = "Background", background = "background_1"},
    { action = "SetCharacter", number = 2, command_list = ["ohm","ohmf"], mood_list = ["Normal","sad"]},
    { action = "Dialog", command = "ohm", mood = "Normal", text = "I am good!"},
    { action = "SetCharacter", number = 3, command_list = ["ohm","ohmf","ohmf"], mood_list = ["sad","Normal","happy"]},
    { action = "Dialog", command = "ohmf", mood = "sad", text = "you are omuba!"},
    { action = "SetCharacter", number = 0},
    { action = "Dialog", command = "no name", text = "I love you!"},
    { action = "Jump", label_id = "Ending", variable = ["HP","ohmLove"], mode = [1,1], gap = [50,100]},
]

[Ending]
script = [
    { action = "Dialog", command = "no name", text = "Hello world!"},
]